[phases.setup]
nixPkgs = ["bun", "openssl", "openssl.dev", "pkg-config"]

[phases.install]
dependsOn = ["setup"]
cmds = ["bun install"]

[phases.build]
dependsOn = ["install"]
cmds = ["cd app/server && bun prisma generate"]

[start]
cmd = "bun --cwd app/server dev"
